version: '3.8'
services:
  webserver:
    image: nginx
    container_name: nginx
    volumes:
      - "nginx-data:/usr/share/nginx/html"
    ports:
      - "80:80"
    networks:
      - "my-network"

  database:
    image: postgres
    container_name: db
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - "my-network"

volumes:
  nginx-data:
  postgres-data:

networks:
  my-network: